### ISSUE TITLE
How to import or add parent-child or multi-level configurations in property stores? (yaml - like)

### ISSUE THREAD

**Issue by sunnyrockstar98** [ff4j/ff4j#489]
Hi @clun 

I see we can add in **property stores** like this - 

`spring.application.name(identifier) and test1(Value)`

But is there a way to import or add configurations in parent-child format like the one below - (like the ones we generally have in spring **application.yml** files)?

```
spring:
  profiles: dev
  application: 
     name: test1
```

Is this configuration format supported?

**Comment by sunnyrockstar98** [comment]
When I try to use the import/export options on the web-console I get properties like name-value pairs. Can't figure out how to use parent-child features on FF4J

**Comment by clun** [comment]
You can load properties/features from a `Yaml` file using the module `ff4j-config-yaml`

Here is a sample code:
https://github.com/ff4j/ff4j/blob/master/ff4j-config-yaml/src/test/java/org/ff4j/parser/yaml/InMemoryFeatureStoreYamlTest.java

Here is a sample file:
https://github.com/ff4j/ff4j/blob/master/ff4j-test/src/main/resources/test-ff4j-features.yml

Now you have paste the keys in `application.yaml` as they are prexided with `ff4j:`

**Comment by sunnyrockstar98** [comment]
Hi @clun 

I see properties like this work - 
```
  properties: 
    - name: a
      #type: org.ff4j.property.PropertyString
      value: AMER
      fixedValues: [AMER, EAST]
    - name: b
      #type: org.ff4j.property.PropertyShort
      type: short
      value: 12
```

But that import doesn't work for configuration in this format  - 


```
ff4j:
  properties:
    spring:
      profiles: dev
      application: 
           name: test1
           value: t4
``` 

I have huge yaml property files.
Can you suggest how can I import these files in my JDBCProperty Store
