### ISSUE TITLE
How to disable REST API and Web Console with ff4j-spring-boot-starter

### ISSUE THREAD

**Issue by hcandraw** [ff4j/ff4j#542]
Hi there, I'm using the `ff4j-spring-boot-starter`.  It seems it automatically exposes REST API at `/api/ff4j` ~and the Web Console at `/ff4j-web-console/home`~ (found out I have to configure the servlet to expose the Web Console).  I can't find any way to disable them.  Can you please enlighten me?  Thanks.

**Comment by clun** [comment]
As of today there is no way to disable  the REST API with the `spring-boot-starter`. I would recommend to use the starter only for the backend admin components and import only the dependency you need in your services (ff4j-core, ff4j-store-X).

**Comment by bbednarek** [comment]
@clun when do you plan to release 1.9?

**Comment by clun** [comment]
1.9 will be released `20/12/2022` (sorry for the wait). 
All tests are cleared, going over a last pass in the tickets.

Sample `application.yml`

```yml
server:
  port: ${PORT:8080}
ff4j:
  api:
    context-path: /api/v1/ff4j     # default '/api/ff4j'
    spring-doc:
      enabled: true                # default 'false'
  audit:
    enabled: true                  # default 'false'
  security:
    enabled: true                  # default 'false'
  web-console:
    context-path: /ff4j-web-console       # default '/ff4j-web-console'
    enabled: true                  # default 'false'
    security:
      enabled: true                # default 'false'
      username: admin              # default 'admin'
      password: admin              # default 'admin'
springdoc:
  swagger-ui:
    tags-sorter: "alpha"
    operations-sorter: "alpha"
```
